trigger:
- main

variables:
  imageName: demo-app

stages:
- stage: Build
  jobs:
  - job: BuildPush
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'reyadevopsacr'
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      name: self-hosted-linux
    steps:
    - task: KubernetesManifest@1
      inputs:
        action: deploy
        kubernetesServiceConnection: 'reyaaks-default'
        manifests: k8s-deployment.yaml
